// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0ksoOPrOyTKDezie57sZojY6WlRnY1d4',
    appId: '1:554521764278:web:62f3d650dd5ea751802117',
    messagingSenderId: '554521764278',
    projectId: 'flutter-dart-project-mobile',
    authDomain: 'flutter-dart-project-mobile.firebaseapp.com',
    storageBucket: 'flutter-dart-project-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4bnTiC90l3JhcQRjdBQH8FILw2Y3HlEU',
    appId: '1:554521764278:android:3713cdae845ee1eb802117',
    messagingSenderId: '554521764278',
    projectId: 'flutter-dart-project-mobile',
    storageBucket: 'flutter-dart-project-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbmILtXDeX4Xot91bXt5iULuPIytWjpME',
    appId: '1:554521764278:ios:ad1ee0a90e80a9a7802117',
    messagingSenderId: '554521764278',
    projectId: 'flutter-dart-project-mobile',
    storageBucket: 'flutter-dart-project-mobile.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbmILtXDeX4Xot91bXt5iULuPIytWjpME',
    appId: '1:554521764278:ios:ad1ee0a90e80a9a7802117',
    messagingSenderId: '554521764278',
    projectId: 'flutter-dart-project-mobile',
    storageBucket: 'flutter-dart-project-mobile.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0ksoOPrOyTKDezie57sZojY6WlRnY1d4',
    appId: '1:554521764278:web:51c21f81bf382374802117',
    messagingSenderId: '554521764278',
    projectId: 'flutter-dart-project-mobile',
    authDomain: 'flutter-dart-project-mobile.firebaseapp.com',
    storageBucket: 'flutter-dart-project-mobile.firebasestorage.app',
  );
}
